spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    #generate-ddl: true
    #hibernate:
      #ddl-auto: create-drop
    #database: h2
  flyway:
    baseline-on-migrate: true